### ISSUE TITLE
Support iOS dylib/executables

### ISSUE THREAD

**Issue by mmastrac** [mmastrac/rust-ctor#10]
This should be a simple `cfg` line but will need testing.

**Comment by sagebind** [comment]
Seemingly constructors are defined in the same way as macOS: https://stackoverflow.com/questions/59271654/what-does-attribute-constructor-compile-to-for-ios-how-to-do-it-in-hand. Testing remains though.

**Comment by luxxxxy** [comment]
Should be closed by #69 (nice)

**Comment by mmastrac** [comment]
Fixed by @luxxxxy, thanks!

**Comment by mmastrac** [comment]
Published as 0.1.15
