### ISSUE TITLE
{con,de}structors do not run when linked with LLD

### ISSUE THREAD

**Issue by arcnmx** [mmastrac/rust-ctor#17]
May be a duplicate of #16? I'm not using clang but it is the easiest way to reproduce the issue if your gcc version doesn't support it:

```
RUSTFLAGS='-C linker=clang -C link-arg=-fuse-ld=lld' cargo test
running 2 tests
test test::test_initialized ... FAILED
test test::test_dylib ... FAILED
```

**Comment by mmastrac** [comment]
Sorry - been slow on responding to these. We _might_ need to implement LLVM's specific handling for constructors to fix this and #16. This might mean shipping some C alongside the library.
