### ISSUE TITLE
Macro reexporting broken in 0.1.24 & 0.1.25

### ISSUE THREAD

**Issue by bearcage** [mmastrac/rust-ctor#241]
The changes from [this diff](https://github.com/mmastrac/rust-ctor/commit/22efb852e1161de4e545daeb2d2768f7ff396c0e) and released in 0.1.24 and the subsequent 0.1.25 (which, incidentally, looks to be [available on crates.io](https://crates.io/crates/ctor/versions) but not reflected in the commit history pushed to github for [`ctor/Cargo.toml`](https://github.com/mmastrac/rust-ctor/commits/master/ctor/Cargo.toml)) refer to `ctor` as a top level module in the [macro callsites which deduplicated the big cfg_attr blocks](https://github.com/mmastrac/rust-ctor/commit/22efb852e1161de4e545daeb2d2768f7ff396c0e#diff-d12aafe6c9cce27052e4f33feb0171e93f6b71970742e5f12d5ee840286c81fbR177). This, unfortunately, results in errors that look like the attached screenshot if you have reexported the ctor attribute macro in a crate of your own.

Specifically, this happens because crates which depend on ctor by another name, or only transitively (as in my use case) will not have `::ctor` available. The usual workaround for this of reexporting dependency macros from your own crate (`::config::premain_support::ctor` in my case) doesn't work if the reexported macro generates references to itself by name. For not-so-procedural macros, `$crate` is available to work around this. There might be a general answer for this for procedural macros, but I'm not aware of one -- I'll take a quick look and see what I can find, though.

![image](https://user-images.githubusercontent.com/596042/196573230-4975a890-066d-4f0e-94f6-e80114bcd34d.png)

**Comment by bearcage** [comment]
Looks like this _can_ be done with proc macros, as of 2019 (last time I looked was a good while before that)! [The `extern_crate_self`](https://github.com/rust-lang/rust/pull/57407), which afaict stabilized in 1.34, allows a local rename of self in the crate that defines the macro -- intended to fix just this problem.

**Comment by bearcage** [comment]
or it will be if I can sort out how exactly that feature's meant to work anyhow

**Comment by mmastrac** [comment]
@bearcage Excellent. If you get it, let me know. 

The alternative is that we can just pass the whole `cfg_attr` array into `quote!`.

**Comment by mmastrac** [comment]
@bearcage I pulled a bit of a quite rework in https://github.com/mmastrac/rust-ctor/commit/27656d9c3acbe9046ba52ecd5e004a929655bb96 - fingers crossed that fixes it.
