### ISSUE TITLE
Support for musl targets

### ISSUE THREAD

**Issue by thedrow** [mmastrac/rust-ctor#25]
As it turns out ctor is not supported on musl targets.
See https://github.com/PyO3/pyo3/issues/599 for example.

Is it possible to implement this crate on musl?
I'm not entirely sure myself.
What do you think?

**Comment by mmastrac** [comment]
I believe that this crate would support musl if all the deps (proc_macro/etc) support musl, as we only use `target_os`:

`            #[cfg_attr(target_os = "linux", link_section = ".init_array")]`

**Comment by thedrow** [comment]
It seems that there is a problem with proc macros in general on musl and its not something you can fix for now.
See https://github.com/PyO3/pyo3/issues/599#issuecomment-529994756
Thanks anyway.

**Comment by mmastrac** [comment]
@thedrow I confirmed that it _does_ work with musl, but you need to cross-compile. This worked on my mac:

```
cross run --frozen --target x86_64-unknown-linux-musl --example example
```
