### ISSUE TITLE
FreeBSD CI

### ISSUE THREAD

**Issue by asomers** [mmastrac/rust-ctor#267]
Thank you for this crate!  I find it useful.  But since it contains OS-dependent code, it should really be tested as widely as possible.  Would you accept a PR to add CI for FreeBSD?  If so, follow the instructions here, but stop at "Post Installation".  Then I'll submit a PR to add the rest.
https://cirrus-ci.org/guide/quick-start/

**Comment by mmastrac** [comment]
I just set this up. PR welcome!
