### ISSUE TITLE
"symbol `init___rust_ctor___ctor` is already defined" after updating ctor from `v0.2.0` -> `v0.2.1`

### ISSUE THREAD

**Issue by alamb** [mmastrac/rust-ctor#283]
Our CI started failing after updating ctor from `v0.2.0` -> `v0.2.1`
https://github.com/apache/arrow-datafusion/issues/6495

```
   Compiling datafusion v25.0.0 (/Users/alamb/Software/arrow-datafusion2/datafusion/core)
error: symbol `init___rust_ctor___ctor` is already defined
   --> datafusion/optimizer/src/scalar_subquery_to_join.rs:311:5
    |
311 |     #[ctor::ctor]
    |     ^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `ctor::ctor` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I haven't had a chance to look into it yet, but wanted to get a ticket filed in case other people hit the same issue

**Comment by mmastrac** [comment]
I think this is from adding #[no_mangle] to the exported symbol. I'll revert that change, but it would be good to get a testcase for it.

**Comment by mmastrac** [comment]
`ctor 0.2.2` is pushed without `#[no_mangle]`. Please let me know if this fixes it.

**Comment by alamb** [comment]
Thanks @mmastrac
