### ISSUE TITLE
The #[link_section] setup generates LLVM error `unsupported relocation of variable` on MacOS with -Zsanitizer=address

### ISSUE THREAD

**Issue by danakj** [mmastrac/rust-ctor#290]
https://bugs.chromium.org/p/chromium/issues/detail?id=1459686

Replacing `#[link_section="__DATA,__mod_init_func"]` with `#[link_section="__DATA_CONST,__mod_init_func"]` resolves the error.

We're using small_ctor in Chromium at the moment, but it uses the same setup.

**Comment by mmastrac** [comment]
Thanks for the report. Released as 0.2.3.

**Comment by danakj** [comment]
Thank you :)
