### ISSUE TITLE
ctor does not work on a cdylib when the "associated" executable is called from the second parent directory

### ISSUE THREAD

**Issue by DasStone** [mmastrac/rust-ctor#291]
# Platform Information (x86-64)
- The bug occurs on Windows (Tested on `Windows 11 Pro 22H2`)
- The bug ***does not*** occur on Linux (Tested on `Ubuntu 22.04` running in `WSL`)
- Information on other Platforms not available

# Bug Description
I currently have a rust library (`crate-type = ["cdylib"]`). Let's say, for sake of argument, that I have an executable `foo.exe` that relies on some of the libraries functions.

Our hypothetical `foo.exe` resides in this example location: `game\build\windows\foo.exe` (The Library is in the same directory).

The `[ctor]` Function will not be called, when foo.exe is invoked from the "parent parent" (i.e. `game`) Directory.

Running `.\build\windows\foo.exe` from within the `game` Directory does not work. It works however from every other location (afaik).

The `[ctor]` is basically doing nothing:
```rust
#[ctor]
fn entry() {
    println!("ctor");
}
```

**Comment by mmastrac** [comment]
Interesting -- would the same binaries behave differently depending on the relative locations from which they are invoked? ie: if you provided a parameter to foo.exe to `DllOpen` the cdylib from different dirs, does it work in one location and not another?

**Comment by mmastrac** [comment]
I found some interesting discussion that _might_ be related: https://devblogs.microsoft.com/cppblog/new-compiler-warnings-for-dynamic-initialization/

**Comment by mmastrac** [comment]
I made a small change in 0.2.4 which _might_ help here -- see if that works for you

**Comment by DasStone** [comment]
Thank you for the replies!

> Interesting -- would the same binaries behave differently depending on the relative locations from which they are invoked? ie: if you provided a parameter to foo.exe to `DllOpen` the cdylib from different dirs, does it work in one location and not another?

I will write a followup comment when I find the time to test this.

> I made a small change in 0.2.4 which _might_ help here -- see if that works for you

Sadly the problem still persists.
