### ISSUE TITLE
Trigger dtors on unload of a shared library

### ISSUE THREAD

**Issue by dtolnay** [mmastrac/rust-ctor#3]
Ctors run when I load a shared library, but its dtors do not run when that library is unloaded.

As you commented in https://github.com/dtolnay/inventory/issues/1#issuecomment-450517561, fixing this may involve changing over from `atexit` to `__cxa_atexit`.

**Comment by mmastrac** [comment]
I spent a little while building up some test cases for this and I _believe_ that this is working for all three platform and `+crt_static` & `-crt_static`:

Linux `+crt_static`: https://travis-ci.org/mmastrac/rust-ctor/jobs/473426254#L519
Linux `-crt_static`: https://travis-ci.org/mmastrac/rust-ctor/jobs/473426254#L552
OSX: `+crt_static`: https://travis-ci.org/mmastrac/rust-ctor/jobs/473426257#L181
OSX: `-crt_static`: https://travis-ci.org/mmastrac/rust-ctor/jobs/473426257#L214
Win: `+crt_static`: https://travis-ci.org/mmastrac/rust-ctor/jobs/473426261#L142
Win: `-crt_static`: https://travis-ci.org/mmastrac/rust-ctor/jobs/473426261#L177

I'm creating a follow-up bug on this to automate some of the testing around this, but for now I think I can call this working. I'll release 0.1.5 with some doc fixes to indicate that this crate works for `bin` and `cdylib` based on these findings.

**Comment by dtolnay** [comment]
Nice, thanks! Confirmed that it works for me on Linux.
