### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by cdbfoster** [mmastrac/rust-ctor#45]
Currently it appears that Android is not supported; [typetag](https://github.com/dtolnay/typetag) fails to deserialize trait objects on Android but not on Linux.  I believe this is due to the fact that ctor does conditional compilation for many target operating systems, but not Android.

Given Android's similarity to Linux, I naively copied the `#[cfg_attr(...)]` lines for "linux" and rewrote them as "android", and this solved the deserialization issue on Android.  Maybe there are some differences between the two that real support should be aware of, but this works for my case, at least. If that's an acceptable solution, I'd be happy to create a PR, otherwise, I wanted to bring this to your attention!

**Comment by mmastrac** [comment]
Happy to take a PR! Mainly just wanted to ensure that someone confirmed it worked.

**Comment by cdbfoster** [comment]
Sounds good! https://github.com/mmastrac/rust-ctor/pull/46 should do the trick; it solves the problem I was having.

**Comment by mmastrac** [comment]
Closed/merged. Fixed in 0.1.13. Thanks for the PR!
