### ISSUE TITLE
Clarify limitation

### ISSUE THREAD

**Issue by noproto** [mmastrac/rust-ctor#60]
In README.md:

> Rust's philosophy is that nothing happens before or after main and this library explicitly subverts that. The code that runs in the ctor and dtor functions should be careful to limit itself to libc functions and code that does not rely on Rust's stdlib services.

The examples given immediately after the warning use stdlib types, and I found a lot of usage of this library with stdlib in the ctor macro. Even println!() seemed to work without a hitch. Would you mind elaborating on this warning? What can we expect, specifically in ctor (not dtor)? Are there examples of what may not work?

**Comment by sagebind** [comment]
One example is using `std::thread` machinery. For example, the following program will unconditionally panic:

```rust
#[ctor::ctor]
fn foo() {
    std::thread::current();
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by CraftSpider** [comment]
In std contexts, this file contains the code actually run to initialize things before `main`:
https://github.com/rust-lang/rust/blob/master/library/std/src/rt.rs

The main things I see (And note that on many platforms, some of these initializers is a noop) are the generic init, the thread guard and naming of main (The thing that allows `std::thread::current()` to work, I suspect but haven't confirmed), and the args init. The generic init doesn't do anything on windows, but on most unix platforms does some stuff to ensure the validity of stdin and stdout in certain cases. The args init doesn't do anything on windows or mac, but on other unix platforms saves argc/argv.

If desired, I can clean that up a bit and add a 'depending on platform, these things may or may not work, and different versions may add new module initialization at will' to clarify.
