### ISSUE TITLE
Add `#[ctor(std)]` and `#[dtor(std)]` to allow safe usage of `std`

### ISSUE THREAD

**Issue by mmastrac** [mmastrac/rust-ctor#7]
`#[ctor]` and `#[dtor]` are run at module init time, not Rust init time, making usage of stdlib risky, unsupported, and often undefined. 

By adding `(std)` to either of the attributes, we could generate the appropriate glue to ensure that we allow safe use of Rust stdlib.

**Comment by sagebind** [comment]
I wonder, what would said glue look like?
