### ISSUE TITLE
Portable library with ctor and statically linked libc for LD_PRELOAD cannot be created

### ISSUE THREAD

**Issue by sriemer** [mmastrac/rust-ctor#86]
I'd like to build a portable dynamic library on Ubuntu with static linking and just a library constructor to be able to use it on Ubuntu and Alpine Linux (glibc based and musl based Linux).

With C code and gcc that is possible by using the following gcc linker options:
`-shared -static -nodefaultlibs -nostdlib -static-libgcc -Wl,--version-script=${PWD}/export.map`
with the `export.map`:
```
{
  local:
    *;
};
```
```
$ ldd mylib.so
        statically linked
```

Now my **attempts to achieve this with Rust** (1.46.0):
`Cargo.toml` parts:
```
[dependencies]
ctor = "0.1.15"
libc-print = "0.1.7"

[lib]
name = "static_lib"
crate_type = ["cdylib"]
proc-macro = true
```

`src/lib.rs`:
```rust
extern crate ctor;
extern crate libc_print;

use ctor::*;
use libc_print::*;

#[ctor]
fn initialize() {
    libc_eprintln!("Initializing");
}
```

I've found two variants that can be built:
1. dynamic linking to C and Rust libraries:
`RUSTFLAGS="-C prefer-dynamic=on -C target-feature=-crt-static" cargo build`
```
$ ldd target/debug/libstatic_lib.so
	linux-vdso.so.1 (0x00007ffd84754000)
	libstd-cf0f33af3a901778.so => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007f10f1b63000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f10f2122000)
```

2. dynamic linking to C libraries only:
`RUSTFLAGS="-C prefer-dynamic=off -C target-feature=+crt-static" cargo build`
```
$ ldd target/debug/libstatic_lib.so 
	linux-vdso.so.1 (0x00007ffc74983000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f84e9146000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f84e9736000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f84e8f27000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f84e8d23000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f84e8b0b000)
```

Setting a different `linker-flavor` according to https://doc.rust-lang.org/rustc/codegen-options/index.html has issues e.g. due to default option `-lgcc_s`. Setting linker-flavor gcc and appending linker options like e.g. `-C link-arg=-static` causes errors while building the dependencies. Using the `x86_64-unknown-linux-musl` target also does not change anything.

Any idea how to get this working? Or is the C code variant the only way to go? TIA

**Comment by mmastrac** [comment]
Could you link it as a static library and pass it off to gcc for the final linkage? Rust _should_ create a C-compatible library in that case and you can pass whatever linker flags you like.

**Comment by sriemer** [comment]
Nope, not working. A static library is too different from a statically linked shared library. Either I get a shared library containing no code or it complains about the usual `relocation R_X86_64_32 against hidden symbol '__TMC_END__' cannot be used when making a shared object` meaning: "You cannot build a statically linked shared library from a static library.".

We decided to go with the C code variant. So closing. Thanks.
