### ISSUE TITLE
ctor does not support taking command line arguments

### ISSUE THREAD

**Issue by sarvi** [mmastrac/rust-ctor#88]
Liux allows the following in constructors to have access to the command line arguments.
```
#[ctor]
fn cfoo(argc: libc::c_int, argv: *const *const libc::c_char) {
}
```

Compilation errors out
```
  Compiling wisktrack v0.1.0 (/ws/sarvi-sjc/wisktrack)
error: custom attribute panicked
   --> src/lib.rs:383:1
    |
383 | #[ctor]
    | ^^^^^^^
    |
    = help: message: #[ctor] methods may not have parameters

```

**Comment by mmastrac** [comment]
Interesting. Is this universal across all platforms? I could consider adding this but we'd have to consider multi-platform support.

**Comment by alecmocatta** [comment]
Last I checked, macOS and glibc on Linux have done this since forever, but
musl on Linux does not.

**Comment by sarvi** [comment]
This is certainly very usefull for linux. The alternative to getting the argc/argv in the constructor is to to read/parse /proc/cmdline which is obviously more work. The parsing of command lines can get complicated pretty fast, when you look at all the complex command lines /bin/sh -c ....... invcations out there.

**Comment by mmastrac** [comment]
I would be open to providing this as some sort of `Option<...>` parameter that would be populated if and only if the underlying libc supports it. Because platform support varies so wildly, I'd be wary of allowing end-users to access the args without some sort of compiler check.

**Comment by mmastrac** [comment]
I dug into Rust's support for ArgsOs and it's pretty likely that all unixes (including musl!) support this style - https://github.com/rust-lang/rust/blob/838325726a05855f10fbb6b3dc7165a7d8dde7b9/library/std/src/sys/unix/args.rs

I suppose that since this is a low-level method it may make sense to just have a nullable const ** for argv that would indicate a lack of platform support.

**Comment by sarvi** [comment]
Looks like 
https://doc.rust-lang.org/stable/std/env/fn.args.html 
might be another way to get at the command line arguments.

"On glibc Linux systems, arguments are retrieved by placing a function in ".init_array". Glibc passes argc, argv, and envp to functions in ".init_array", as a non-standard extension. This allows std::env::args to work even in a cdylib or staticlib, as it does on macOS and Windows."

**Comment by mmastrac** [comment]
@sarvi Yep, that'll work for std programs. I can see that this could be useful to provide args, but I think it would require porting the std Args support to an external crate that ctor could make use of. This is an interesting problem to consider and I'll leave it open in the meantime!
