### ISSUE TITLE
#[ctor] on static unsound in presence of threads

### ISSUE THREAD

**Issue by thomcc** [mmastrac/rust-ctor#95]
If you use the ctor macro to initialize a static, it gets stored in a static mut without synchronization. This is not thread safe.

It's possible to create threads from inside `#[ctor]` (yes, really, it works), and allows you to have data races from completely safe code — you can't assume these are running in a single-threaded environment.

I also would suspect there are cases where the constructor functions are called in a way that has nontrivial ordering behavior, as C++ goes out of its way to allow this, but I don't know for sure.

**Comment by mmastrac** [comment]
Correct - these should probably use unsafe syntax to indicate this. These were originally concocted when `const` was in its infancy and I think they can be deprecated.

**Comment by mmastrac** [comment]
I'd like to protect these statics from access before main with an `AtomicBoolean`, but I need to ponder how I can ensure this will work. Ideally I'd like something that happens after all the ctors have finished (ideally when main is running or just about to run)

**Comment by thomcc** [comment]
Did this get fixed?
