### ISSUE TITLE
Inserting extern "Rust" (e.g. default ABI) functions into these symbol arrays is very dodgy

### ISSUE THREAD

**Issue by thomcc** [mmastrac/rust-ctor#96]
https://github.com/mmastrac/rust-ctor/blob/master/ctor/src/lib.rs#L222-L224 are missing extern "C". It looks like the others might be too since it comes from quote. These are called from C using the default ABI for C, and so should be extern "C".

I think Rust and C have the same calling convention for 0-arg functions (this is not a given, but it seems likely in practice), so it's probably fine, but it should probably be fixed.

**Comment by mmastrac** [comment]
Should be pretty straightforward.

**Comment by CraftSpider** [comment]
The function branch in ctor and dtor preserves the ABI of the user, but defaults to Rust also. Should there maybe be a warning on explicit ABI that's not C / should it actually convert no explicit ABI into `C` instead of `Rust`?

**Comment by mmastrac** [comment]
What we should probably do is always export a "C" ABI function that calls into the function provided by the user. LLVM _should_ be able to inline that single call level correctly, regardless of ABI.

**Comment by CraftSpider** [comment]
Makes sense. That design makes me think it would make sense to change quote! to something a bit like
```rs
#[used]
#[...]
static ident___rust_ctor___ctor: unsafe extern "C" fn() = {
    ...
    wrapper_func
}

#function
```
for functions, so the annotated function is callable exactly by name with the correct ABI, and the ctor function is fully generated
